### ISSUE TITLE
Training data for KITTI test submissio

### ISSUE THREAD

**Issue by charmeleonz** [SPengLiang/LPCG#10]
Hi,

May I know whether you used all the 7k training and validation samples as labelled training data for your reported results (high accuracy mode) on the KITTI test server?

Thanks.

**Comment by SPengLiang** [comment]
Sorry for the late reply.  For the KITTI test server, we use the 3.7k labels (in the training split), but we employ other unlabeled data and generate pseudo labels for training.

**Comment by charmeleonz** [comment]
Thank you.
